<!-- Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ -->
<script setup>
import {reactive,ref} from 'vue';import {request} from '../api'
const fields=[{"key": "fileNo", "label": "文件编号", "type": "text"}, {"key": "fileSizeBytes", "label": "文件大小(字节)", "type": "number"}, {"key": "versionCount", "label": "版本数量", "type": "number"}, {"key": "classification", "label": "数据分级", "type": "text"}, {"key": "shareDays", "label": "共享有效天数", "type": "number"}, {"key": "retentionDays", "label": "保留期限(天)", "type": "number"}, {"key": "checksumVerified", "label": "文件哈希已校验", "type": "boolean"}, {"key": "permissionReviewed", "label": "访问权限已复核", "type": "boolean"}, {"key": "watermarkEnabled", "label": "已启用水印", "type": "boolean"}]
const form=reactive({"fileNo": "DOC-2026-0088", "fileSizeBytes": 1048576, "versionCount": 3, "classification": "INTERNAL", "shareDays": 7, "retentionDays": 365, "checksumVerified": true, "permissionReviewed": true, "watermarkEnabled": true}),result=ref(null),error=ref(''),busy=ref(false)
function payload(){const data={};for(const field of fields){const value=form[field.key];if(field.type==='number')data[field.key]=Number(value);else data[field.key]=value}return data}
async function run(){busy.value=true;error.value='';try{result.value=await request('/api/domain/decision',{method:'POST',body:JSON.stringify(payload())})}catch(e){error.value=e.message}finally{busy.value=false}}
const show=value=>Array.isArray(value)?(value.length?value.join('；'):'无'):typeof value==='object'?JSON.stringify(value):String(value)
</script>
<template><section class="rule-head"><div><span>DOMAIN CONTROL</span><h3>企业网盘与文档管理系统领域规则验证</h3><p>为企业文件提供统一空间、精细权限、版本协作和全生命周期审计，由服务端返回可审计决策、评分、指标和处置动作。</p></div><b>服务端强校验</b></section><section class="rule-layout"><form class="rule-form" @submit.prevent="run"><label v-for="field in fields" :key="field.key"><span>{{field.label}}</span><span v-if="field.type==='boolean'" class="switch"><input v-model="form[field.key]" type="checkbox">{{form[field.key]?'是':'否'}}</span><input v-else v-model="form[field.key]" :type="field.type" :step="field.type==='number'?'any':undefined" required></label><button class="run" :disabled="busy">{{busy?'正在校验…':'执行规则校验'}}</button><p v-if="error" class="rule-error">{{error}}</p></form><aside class="result"><template v-if="result"><span>DECISION</span><h3>{{result.decision}}</h3><strong>评分 {{result.score}} / 100</strong><dl><template v-for="(value,key) in result.metrics" :key="key"><dt>{{key}}</dt><dd>{{show(value)}}</dd></template></dl><h4>处置动作</h4><p v-for="item in result.actions" :key="item">· {{item}}</p></template><div v-else class="empty"><b>等待评估</b><p>填写业务数据后执行企业级领域规则。</p></div></aside></section></template>
<style scoped>.rule-head{display:flex;align-items:end;justify-content:space-between;padding:26px 30px;margin-bottom:18px;background:#fff;border:1px solid #e2e8eb;border-radius:14px}.rule-head span,.result>span{font-size:12px;letter-spacing:.16em;color:#61727b}.rule-head h3{font-size:24px;margin:7px 0}.rule-head p{margin:0;color:#667780}.rule-head>b{padding:8px 12px;border-radius:20px;background:#e8f3ee;color:#237052;font-size:13px}.rule-layout{display:grid;grid-template-columns:minmax(0,1.25fr) minmax(320px,.75fr);gap:18px}.rule-form,.result{background:#fff;border:1px solid #e2e8eb;border-radius:14px;padding:28px}.rule-form{display:grid;grid-template-columns:1fr 1fr;gap:18px}.rule-form label{display:flex;flex-direction:column;gap:8px;font-size:13px;color:#44545d}.rule-form input{box-sizing:border-box;width:100%;border:1px solid #ccd6db;border-radius:8px;padding:11px 12px;font:inherit;background:#fbfcfd}.switch{display:flex;align-items:center;gap:8px;height:40px}.switch input{width:18px}.run,.rule-error{grid-column:1/-1}.run{border:0;border-radius:8px;padding:13px;background:#234f66;color:#fff;font-weight:700}.result h3{font-size:25px;margin:8px 0}.result dl{margin:15px 0}.result dt{font-size:12px;color:#78868e;margin-top:10px}.result dd{margin:3px 0;border-bottom:1px solid #edf0f2;padding-bottom:8px}.empty{display:grid;place-content:center;min-height:260px;color:#75838a}.rule-error{color:#a53535}@media(max-width:900px){.rule-layout{grid-template-columns:1fr}.rule-form{grid-template-columns:1fr}}</style>
