/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.drive;import org.junit.jupiter.api.Test;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;import org.springframework.http.MediaType;import org.springframework.test.web.servlet.*;import java.util.regex.Pattern;import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.httpBasic;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest@AutoConfigureMockMvc class DriveCoreApiTests{@Autowired MockMvc mvc;static final String A="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",B="bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb";
 @Test void documentMaintainsImmutableSequentialVersions()throws Exception{long id=create("DOC-CORE-1","INTERNAL",A);mvc.perform(post("/api/core/drive/documents/"+id+"/versions").with(httpBasic("operator","operator123")).contentType(MediaType.APPLICATION_JSON).content(version(B))).andExpect(status().isOk()).andExpect(jsonPath("$.data.versionNo").value(2));mvc.perform(get("/api/core/drive/documents/"+id+"/versions").with(httpBasic("operator","operator123"))).andExpect(jsonPath("$.data.length()").value(2));}
 @Test void duplicateChecksumIsIdempotent()throws Exception{long id=create("DOC-CORE-2","INTERNAL",A);mvc.perform(post("/api/core/drive/documents/"+id+"/versions").with(httpBasic("operator","operator123")).contentType(MediaType.APPLICATION_JSON).content(version(A))).andExpect(status().isOk()).andExpect(jsonPath("$.data.versionNo").value(1));}
 @Test void confidentialShareRequiresPasswordAndEnforcesDownloadLimit()throws Exception{long id=create("DOC-CORE-3","CONFIDENTIAL",A);mvc.perform(post("/api/admin/core/drive/documents/"+id+"/shares").with(httpBasic("admin","admin123")).contentType(MediaType.APPLICATION_JSON).content("{\"expiresInHours\":24,\"maxDownloads\":1,\"password\":\"safe-pass\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.passwordHash").doesNotExist()).andDo(result->{String body=result.getResponse().getContentAsString();var m=Pattern.compile("\\\"token\\\":\\\"([^\\\"]+)").matcher(body);m.find();String token=m.group(1);mvc.perform(post("/api/public/drive/shares/"+token+"/access").contentType(MediaType.APPLICATION_JSON).content("{\"password\":\"wrong\"}")).andExpect(status().isForbidden());mvc.perform(post("/api/public/drive/shares/"+token+"/access").contentType(MediaType.APPLICATION_JSON).content("{\"password\":\"safe-pass\"}")).andExpect(status().isOk());mvc.perform(post("/api/public/drive/shares/"+token+"/access").contentType(MediaType.APPLICATION_JSON).content("{\"password\":\"safe-pass\"}")).andExpect(status().isGone());});}
 @Test void operatorCannotCreateShareOrArchive()throws Exception{long id=create("DOC-CORE-4","PUBLIC",A);mvc.perform(post("/api/admin/core/drive/documents/"+id+"/archive").with(httpBasic("operator","operator123"))).andExpect(status().isForbidden());}
 @Test void archivingRevokesFurtherVersionChanges()throws Exception{long id=create("DOC-CORE-5","PUBLIC",A);mvc.perform(post("/api/admin/core/drive/documents/"+id+"/archive").with(httpBasic("admin","admin123"))).andExpect(status().isOk());mvc.perform(post("/api/core/drive/documents/"+id+"/versions").with(httpBasic("operator","operator123")).contentType(MediaType.APPLICATION_JSON).content(version(B))).andExpect(status().isConflict());}
 @Test void checkoutPreventsConcurrentOverwriteAndCheckinReleasesLock()throws Exception{long id=create("DOC-CORE-6","INTERNAL",A);mvc.perform(post("/api/core/drive/documents/"+id+"/checkout").with(httpBasic("operator","operator123")).contentType(MediaType.APPLICATION_JSON).content("{\"expiresInHours\":8}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.checkedOutBy").value("operator"));mvc.perform(post("/api/core/drive/documents/"+id+"/versions").with(httpBasic("admin","admin123")).contentType(MediaType.APPLICATION_JSON).content(version(B))).andExpect(status().isConflict());mvc.perform(post("/api/core/drive/documents/"+id+"/checkin").with(httpBasic("operator","operator123")).contentType(MediaType.APPLICATION_JSON).content(version(B))).andExpect(status().isOk()).andExpect(jsonPath("$.data.versionNo").value(2));mvc.perform(get("/api/core/drive/documents/"+id).with(httpBasic("operator","operator123"))).andExpect(jsonPath("$.data.checkedOutBy").doesNotExist());}
 @Test void onlyAdministratorCanForceUnlock()throws Exception{long id=create("DOC-CORE-7","INTERNAL",A);mvc.perform(post("/api/core/drive/documents/"+id+"/checkout").with(httpBasic("operator","operator123")).contentType(MediaType.APPLICATION_JSON).content("{\"expiresInHours\":8}")).andExpect(status().isOk());mvc.perform(post("/api/admin/core/drive/documents/"+id+"/force-unlock").with(httpBasic("operator","operator123"))).andExpect(status().isForbidden());mvc.perform(post("/api/admin/core/drive/documents/"+id+"/force-unlock").with(httpBasic("admin","admin123"))).andExpect(status().isOk()).andExpect(jsonPath("$.data.checkedOutBy").doesNotExist());}
 private long create(String no,String classification,String checksum)throws Exception{MvcResult r=mvc.perform(post("/api/core/drive/documents").with(httpBasic("operator","operator123")).contentType(MediaType.APPLICATION_JSON).content("{\"documentNo\":\""+no+"\",\"name\":\"企业制度.pdf\",\"owner\":\"行政部\",\"classification\":\""+classification+"\",\"checksum\":\""+checksum+"\",\"sizeBytes\":1024,\"changeNote\":\"初版\"}")).andExpect(status().isOk()).andReturn();var m=Pattern.compile("\\\"id\\\":(\\d+)").matcher(r.getResponse().getContentAsString());m.find();return Long.parseLong(m.group(1));}private String version(String checksum){return "{\"checksum\":\""+checksum+"\",\"sizeBytes\":2048,\"changeNote\":\"修订\"}";}
}
