/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.drive.service;
import com.fasterxml.jackson.annotation.JsonIgnore;import jakarta.persistence.*;import jakarta.validation.constraints.*;import org.springframework.http.HttpStatus;import org.springframework.security.core.context.SecurityContextHolder;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.server.ResponseStatusException;
import java.time.LocalDateTime;import java.util.*;
@Service public class DriveCoreService{
 private final EntityManager em;private final PasswordEncoder encoder;public DriveCoreService(EntityManager em,PasswordEncoder encoder){this.em=em;this.encoder=encoder;}
 @Transactional public Document create(CreateDocumentRequest r){if(!byNo(r.documentNo()).isEmpty())throw conflict("文档编号已存在");Document d=new Document(r.documentNo(),r.name(),r.owner(),r.classification());em.persist(d);em.flush();addVersion(d.id,new VersionRequest(r.checksum(),r.sizeBytes(),r.changeNote()));return d;}
 public List<Document> documents(String classification){return em.createQuery("select d from DriveDocument d where (:c is null or d.classification=:c) order by d.updatedAt desc",Document.class).setParameter("c",blank(classification)?null:classification).getResultList();}
 public Document detail(Long id){return get(id);}
 public List<DocumentVersion> versions(Long id){get(id);return em.createQuery("select v from DriveDocumentVersion v where v.documentId=:id order by v.versionNo desc",DocumentVersion.class).setParameter("id",id).getResultList();}
 @Transactional public DocumentVersion addVersion(Long id,VersionRequest r){Document d=getLocked(id);if(!"ACTIVE".equals(d.status))throw conflict("归档文档不能新增版本");expireCheckout(d);if(checkoutActive(d)&&!operator().equals(d.checkedOutBy))throw conflict("文档已被 "+d.checkedOutBy+" 签出，禁止并发覆盖");List<DocumentVersion> same=em.createQuery("select v from DriveDocumentVersion v where v.documentId=:id and v.checksum=:checksum",DocumentVersion.class).setParameter("id",id).setParameter("checksum",r.checksum()).getResultList();if(!same.isEmpty())return same.getFirst();int next=d.currentVersion+1;DocumentVersion v=new DocumentVersion(d.id,next,r.checksum(),r.sizeBytes(),r.changeNote(),operator());em.persist(v);d.currentVersion=next;d.currentChecksum=r.checksum();d.updatedAt=LocalDateTime.now();return v;}
 @Transactional public Document checkout(Long id,CheckoutRequest r){Document d=getLocked(id);if(!"ACTIVE".equals(d.status))throw conflict("归档文档不能签出");expireCheckout(d);if(checkoutActive(d)&&!operator().equals(d.checkedOutBy))throw conflict("文档已被 "+d.checkedOutBy+" 签出");d.checkedOutBy=operator();d.checkedOutAt=LocalDateTime.now();d.checkoutExpiresAt=d.checkedOutAt.plusHours(r.expiresInHours());return d;}
 @Transactional public DocumentVersion checkin(Long id,VersionRequest r){Document d=getLocked(id);expireCheckout(d);if(!checkoutActive(d)||!operator().equals(d.checkedOutBy))throw conflict("只有当前签出人可以签入新版本");DocumentVersion v=addVersion(id,r);d.checkedOutBy=null;d.checkedOutAt=null;d.checkoutExpiresAt=null;return v;}
 @Transactional public Document forceUnlock(Long id){Document d=getLocked(id);d.checkedOutBy=null;d.checkedOutAt=null;d.checkoutExpiresAt=null;return d;}
 @Transactional public Document archive(Long id){Document d=getLocked(id);d.status="ARCHIVED";d.updatedAt=LocalDateTime.now();em.createQuery("update DriveSecureShare s set s.revoked=true where s.documentId=:id").setParameter("id",id).executeUpdate();return d;}
 @Transactional public SecureShare createShare(Long id,CreateShareRequest r){Document d=getLocked(id);if(!"ACTIVE".equals(d.status))throw conflict("归档文档不能共享");if(Set.of("CONFIDENTIAL","SECRET").contains(d.classification)&&blank(r.password()))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"敏感文档共享必须设置访问密码");SecureShare s=new SecureShare(d.id,UUID.randomUUID().toString().replace("-",""),LocalDateTime.now().plusHours(r.expiresInHours()),r.maxDownloads(),blank(r.password())?null:encoder.encode(r.password()),operator());em.persist(s);return s;}
 @Transactional public ShareAccess access(String token,ShareAccessRequest r){List<SecureShare> found=em.createQuery("select s from DriveSecureShare s where s.token=:token",SecureShare.class).setParameter("token",token).setLockMode(LockModeType.PESSIMISTIC_WRITE).getResultList();if(found.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND,"共享链接不存在");SecureShare s=found.getFirst();if(s.revoked)throw new ResponseStatusException(HttpStatus.GONE,"共享链接已撤销");if(LocalDateTime.now().isAfter(s.expiresAt))throw new ResponseStatusException(HttpStatus.GONE,"共享链接已过期");if(s.downloadCount>=s.maxDownloads)throw new ResponseStatusException(HttpStatus.GONE,"共享下载次数已用尽");if(s.passwordHash!=null&&!encoder.matches(r.password()==null?"":r.password(),s.passwordHash))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"共享访问密码错误");Document d=get(s.documentId);s.downloadCount++;return new ShareAccess(d.documentNo,d.name,d.classification,d.currentVersion,d.currentChecksum,s.downloadCount,s.maxDownloads);}
 @Transactional public SecureShare revoke(Long shareId){SecureShare s=em.find(SecureShare.class,shareId,LockModeType.PESSIMISTIC_WRITE);if(s==null)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"共享记录不存在");s.revoked=true;return s;}
 private List<Document> byNo(String no){return em.createQuery("select d from DriveDocument d where d.documentNo=:no",Document.class).setParameter("no",no).getResultList();}
 private Document get(Long id){Document d=em.find(Document.class,id);if(d==null)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"文档不存在");return d;}private Document getLocked(Long id){Document d=em.find(Document.class,id,LockModeType.PESSIMISTIC_WRITE);if(d==null)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"文档不存在");return d;}
 private boolean checkoutActive(Document d){return d.checkedOutBy!=null&&d.checkoutExpiresAt!=null&&LocalDateTime.now().isBefore(d.checkoutExpiresAt);}private void expireCheckout(Document d){if(d.checkoutExpiresAt!=null&&!LocalDateTime.now().isBefore(d.checkoutExpiresAt)){d.checkedOutBy=null;d.checkedOutAt=null;d.checkoutExpiresAt=null;}}private boolean blank(String v){return v==null||v.isBlank();}private String operator(){var a=SecurityContextHolder.getContext().getAuthentication();return a==null?"system":a.getName();}private ResponseStatusException conflict(String m){return new ResponseStatusException(HttpStatus.CONFLICT,m);}
 public record CreateDocumentRequest(@NotBlank@Size(max=50)String documentNo,@NotBlank@Size(max=160)String name,@NotBlank@Size(max=80)String owner,@Pattern(regexp="PUBLIC|INTERNAL|CONFIDENTIAL|SECRET")String classification,@Pattern(regexp="[a-fA-F0-9]{64}")String checksum,@Positive long sizeBytes,@Size(max=300)String changeNote){}
 public record VersionRequest(@Pattern(regexp="[a-fA-F0-9]{64}")String checksum,@Positive long sizeBytes,@Size(max=300)String changeNote){}
 public record CheckoutRequest(@Min(1)@Max(72)int expiresInHours){}
 public record CreateShareRequest(@Min(1)@Max(720)int expiresInHours,@Min(1)@Max(1000)int maxDownloads,@Size(max=100)String password){}
 public record ShareAccessRequest(@Size(max=100)String password){}public record ShareAccess(String documentNo,String name,String classification,int version,String checksum,int downloads,int maxDownloads){}
 @Entity(name="DriveDocument")@Table(name="drive_documents",uniqueConstraints=@UniqueConstraint(columnNames="documentNo"))public static class Document{@Id@GeneratedValue(strategy=GenerationType.IDENTITY)public Long id;@Column(nullable=false,length=50)public String documentNo;@Column(nullable=false,length=160)public String name;@Column(nullable=false,length=80)public String owner;@Column(nullable=false,length=20)public String classification;@Column(nullable=false,length=20)public String status;public int currentVersion;@Column(length=64)public String currentChecksum;@Column(length=80)public String checkedOutBy;public LocalDateTime checkedOutAt;public LocalDateTime checkoutExpiresAt;public LocalDateTime createdAt;public LocalDateTime updatedAt;@Version public long rowVersion;protected Document(){}Document(String no,String name,String owner,String classification){this.documentNo=no;this.name=name;this.owner=owner;this.classification=classification;this.status="ACTIVE";this.createdAt=this.updatedAt=LocalDateTime.now();}public boolean isCheckedOut(){return checkedOutBy!=null&&checkoutExpiresAt!=null&&LocalDateTime.now().isBefore(checkoutExpiresAt);}}
 @Entity(name="DriveDocumentVersion")@Table(name="drive_document_versions",uniqueConstraints={@UniqueConstraint(columnNames={"documentId","versionNo"}),@UniqueConstraint(columnNames={"documentId","checksum"})})public static class DocumentVersion{@Id@GeneratedValue(strategy=GenerationType.IDENTITY)public Long id;public Long documentId;public int versionNo;@Column(nullable=false,length=64)public String checksum;public long sizeBytes;@Column(length=300)public String changeNote;@Column(nullable=false,length=80)public String uploadedBy;public LocalDateTime uploadedAt;protected DocumentVersion(){}DocumentVersion(Long documentId,int versionNo,String checksum,long size,String note,String by){this.documentId=documentId;this.versionNo=versionNo;this.checksum=checksum;this.sizeBytes=size;this.changeNote=note;this.uploadedBy=by;this.uploadedAt=LocalDateTime.now();}}
 @Entity(name="DriveSecureShare")@Table(name="drive_secure_shares",uniqueConstraints=@UniqueConstraint(columnNames="token"))public static class SecureShare{@Id@GeneratedValue(strategy=GenerationType.IDENTITY)public Long id;public Long documentId;@Column(nullable=false,length=40)public String token;public LocalDateTime expiresAt;public int maxDownloads;public int downloadCount;@JsonIgnore@Column(length=100)public String passwordHash;public boolean revoked;@Column(nullable=false,length=80)public String createdBy;public LocalDateTime createdAt;protected SecureShare(){}SecureShare(Long documentId,String token,LocalDateTime expires,int max,String hash,String by){this.documentId=documentId;this.token=token;this.expiresAt=expires;this.maxDownloads=max;this.passwordHash=hash;this.createdBy=by;this.createdAt=LocalDateTime.now();}}
}
